version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: maid-service-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: maid-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: maid-service-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/maid-service
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: maid-service-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data: